spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tokki?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: never

server:
  port: 4000

firebase:
  project-id: ${FIREBASE_PROJECT_ID:}
  client-email: ${FIREBASE_CLIENT_EMAIL:}
  private-key: ${FIREBASE_PRIVATE_KEY:}

admin:
  secret-key: ${ADMIN_SECRET_KEY:}
