spring:
  config:
    import:
      - optional:file:../.env[.properties]
      - optional:file:.env[.properties]
  application:
    name: tokki
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME:${MYSQL_USERNAME}}
    password: ${SPRING_DATASOURCE_PASSWORD:${MYSQL_PASSWORD}}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

server:
  port: ${SERVER_PORT:8080}
  servlet:
    session:
      cookie:
        same-site: lax
        http-only: true
        secure: false

tokki:
  frontend:
    login-url: ${TOKKI_FRONTEND_LOGIN_URL:http://localhost:5173/login}
    callback-url: ${TOKKI_FRONTEND_CALLBACK_URL:http://localhost:5173/login/callback}
  admin:
    secret-key: ${ADMIN_SECRET_KEY}
  jwt:
    secret: ${JWT_SECRET}
